"""Cloud message types and structures for MentraOS communication.

Auto-generated by Claude. Todo: clean up this file and remove unused message types.
"""

from enum import Enum


class AppToCloudMessageType(Enum):
    """Message types sent from app to MentraOS cloud."""

    # Audio control
    AUDIO_PLAY_REQUEST = "audio_play_request"
    AUDIO_PAUSE_REQUEST = "audio_pause_request"
    AUDIO_RESUME_REQUEST = "audio_resume_request"
    AUDIO_STOP_REQUEST = "audio_stop_request"

    # Subscription management
    SUBSCRIBE = "SUBSCRIBE"
    UNSUBSCRIBE = "UNSUBSCRIBE"

    # Session control
    APP_READY = "APP_READY"
    APP_STOPPED = "APP_STOPPED"

    # Custom messages
    CUSTOM = "CUSTOM"


class CloudToAppMessageType(Enum):
    """Message types sent from MentraOS cloud to app."""

    # Audio responses
    AUDIO_PLAY_RESPONSE = "audio_play_response"

    # Session events
    SESSION_STARTED = "session_started"
    SESSION_ENDED = "session_ended"

    # Error messages
    ERROR = "error"
